### ISSUE TITLE
2-아키텍처 개요

### ISSUE THREAD

**Issue by wisdom08** [wisdom08/book-review#2]
계층 구조 아키텍처
- 표현 -> 응용 -> 도메인 -> 인프라스트럭처
- 계층 구조는 상위 계층에서 하위 계층의로의 의존만 존재한다. 

DIP(Dependency Inversion Principle)
- 의존 역전 원칙
  - 저수준 모듈이 고수준 모듈에 의존하는 것
    - 저수준 모듈: 고수준 모듈의 기능을 구현하기 위해 필요한 하위 기능의 실제 구현인 모듈
    - 고수준 모듈: 의미 있는 단일 기능을 제공하는 모듈 
  - 고수준 모듈이 저수준 모듈에 의존하지 않도록 하기 위한 목적

도메인 영역의 주요 구성요소
- entity
- value
- aggregate
  - 관련 객체를 하나로 묶은 군집 
    - ex) 주문 
- repository
- domain service

### 의견
- 계층 구조가 상위에서 하위로만 의존하게 된다. 그런데 그 과정을 막연하고, 추상적인 거에서 구체적인 걸로 '구체화하는 과정'이라는 스터디 팀원 분의 설명이 인상적이었음.

**Comment by jinaSE0** [comment]
오,, 어떻게 마일 스톤 이용해서 하신다는 건지 감이 안왔는데 이렇게 활용할 수 있군요,,,! 배워갑니다 선생님 <3
